# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AdGroupResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ad_group_id: str=None, ad_group_name: str=None, campaign_id: str=None):  # noqa: E501
        """AdGroupResponse - a model defined in Swagger

        :param ad_group_id: The ad_group_id of this AdGroupResponse.  # noqa: E501
        :type ad_group_id: str
        :param ad_group_name: The ad_group_name of this AdGroupResponse.  # noqa: E501
        :type ad_group_name: str
        :param campaign_id: The campaign_id of this AdGroupResponse.  # noqa: E501
        :type campaign_id: str
        """
        self.swagger_types = {
            'ad_group_id': str,
            'ad_group_name': str,
            'campaign_id': str
        }

        self.attribute_map = {
            'ad_group_id': 'AdGroupId',
            'ad_group_name': 'AdGroupName',
            'campaign_id': 'CampaignId'
        }
        self._ad_group_id = ad_group_id
        self._ad_group_name = ad_group_name
        self._campaign_id = campaign_id

    @classmethod
    def from_dict(cls, dikt) -> 'AdGroupResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdGroupResponse of this AdGroupResponse.  # noqa: E501
        :rtype: AdGroupResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ad_group_id(self) -> str:
        """Gets the ad_group_id of this AdGroupResponse.

        The ID of the created Ad Group.  # noqa: E501

        :return: The ad_group_id of this AdGroupResponse.
        :rtype: str
        """
        return self._ad_group_id

    @ad_group_id.setter
    def ad_group_id(self, ad_group_id: str):
        """Sets the ad_group_id of this AdGroupResponse.

        The ID of the created Ad Group.  # noqa: E501

        :param ad_group_id: The ad_group_id of this AdGroupResponse.
        :type ad_group_id: str
        """

        self._ad_group_id = ad_group_id

    @property
    def ad_group_name(self) -> str:
        """Gets the ad_group_name of this AdGroupResponse.

        The name of the created Ad Group.  # noqa: E501

        :return: The ad_group_name of this AdGroupResponse.
        :rtype: str
        """
        return self._ad_group_name

    @ad_group_name.setter
    def ad_group_name(self, ad_group_name: str):
        """Sets the ad_group_name of this AdGroupResponse.

        The name of the created Ad Group.  # noqa: E501

        :param ad_group_name: The ad_group_name of this AdGroupResponse.
        :type ad_group_name: str
        """

        self._ad_group_name = ad_group_name

    @property
    def campaign_id(self) -> str:
        """Gets the campaign_id of this AdGroupResponse.

        The ID of the Campaign that owns this Ad Group.  # noqa: E501

        :return: The campaign_id of this AdGroupResponse.
        :rtype: str
        """
        return self._campaign_id

    @campaign_id.setter
    def campaign_id(self, campaign_id: str):
        """Sets the campaign_id of this AdGroupResponse.

        The ID of the Campaign that owns this Ad Group.  # noqa: E501

        :param campaign_id: The campaign_id of this AdGroupResponse.
        :type campaign_id: str
        """

        self._campaign_id = campaign_id
