# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AdvertiserResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, advertiser_id: str=None):  # noqa: E501
        """AdvertiserResponse - a model defined in Swagger

        :param advertiser_id: The advertiser_id of this AdvertiserResponse.  # noqa: E501
        :type advertiser_id: str
        """
        self.swagger_types = {
            'advertiser_id': str
        }

        self.attribute_map = {
            'advertiser_id': 'AdvertiserId'
        }
        self._advertiser_id = advertiser_id

    @classmethod
    def from_dict(cls, dikt) -> 'AdvertiserResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdvertiserResponse of this AdvertiserResponse.  # noqa: E501
        :rtype: AdvertiserResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def advertiser_id(self) -> str:
        """Gets the advertiser_id of this AdvertiserResponse.

        The platform ID of the created advertiser.  # noqa: E501

        :return: The advertiser_id of this AdvertiserResponse.
        :rtype: str
        """
        return self._advertiser_id

    @advertiser_id.setter
    def advertiser_id(self, advertiser_id: str):
        """Sets the advertiser_id of this AdvertiserResponse.

        The platform ID of the created advertiser.  # noqa: E501

        :param advertiser_id: The advertiser_id of this AdvertiserResponse.
        :type advertiser_id: str
        """

        self._advertiser_id = advertiser_id
