# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.advertiser_overview_response_campaigns import AdvertiserOverviewResponseCampaigns  # noqa: F401,E501
from swagger_server.models.advertiser_overview_response_creatives import AdvertiserOverviewResponseCreatives  # noqa: F401,E501
from swagger_server import util


class AdvertiserOverviewResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, advertiser_id: str=None, advertiser_name: str=None, campaigns: List[AdvertiserOverviewResponseCampaigns]=None, creatives: List[AdvertiserOverviewResponseCreatives]=None):  # noqa: E501
        """AdvertiserOverviewResponse - a model defined in Swagger

        :param advertiser_id: The advertiser_id of this AdvertiserOverviewResponse.  # noqa: E501
        :type advertiser_id: str
        :param advertiser_name: The advertiser_name of this AdvertiserOverviewResponse.  # noqa: E501
        :type advertiser_name: str
        :param campaigns: The campaigns of this AdvertiserOverviewResponse.  # noqa: E501
        :type campaigns: List[AdvertiserOverviewResponseCampaigns]
        :param creatives: The creatives of this AdvertiserOverviewResponse.  # noqa: E501
        :type creatives: List[AdvertiserOverviewResponseCreatives]
        """
        self.swagger_types = {
            'advertiser_id': str,
            'advertiser_name': str,
            'campaigns': List[AdvertiserOverviewResponseCampaigns],
            'creatives': List[AdvertiserOverviewResponseCreatives]
        }

        self.attribute_map = {
            'advertiser_id': 'AdvertiserId',
            'advertiser_name': 'AdvertiserName',
            'campaigns': 'Campaigns',
            'creatives': 'Creatives'
        }
        self._advertiser_id = advertiser_id
        self._advertiser_name = advertiser_name
        self._campaigns = campaigns
        self._creatives = creatives

    @classmethod
    def from_dict(cls, dikt) -> 'AdvertiserOverviewResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdvertiserOverviewResponse of this AdvertiserOverviewResponse.  # noqa: E501
        :rtype: AdvertiserOverviewResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def advertiser_id(self) -> str:
        """Gets the advertiser_id of this AdvertiserOverviewResponse.

        The platform ID of the advertiser.  # noqa: E501

        :return: The advertiser_id of this AdvertiserOverviewResponse.
        :rtype: str
        """
        return self._advertiser_id

    @advertiser_id.setter
    def advertiser_id(self, advertiser_id: str):
        """Sets the advertiser_id of this AdvertiserOverviewResponse.

        The platform ID of the advertiser.  # noqa: E501

        :param advertiser_id: The advertiser_id of this AdvertiserOverviewResponse.
        :type advertiser_id: str
        """

        self._advertiser_id = advertiser_id

    @property
    def advertiser_name(self) -> str:
        """Gets the advertiser_name of this AdvertiserOverviewResponse.

        The name of the advertiser.  # noqa: E501

        :return: The advertiser_name of this AdvertiserOverviewResponse.
        :rtype: str
        """
        return self._advertiser_name

    @advertiser_name.setter
    def advertiser_name(self, advertiser_name: str):
        """Sets the advertiser_name of this AdvertiserOverviewResponse.

        The name of the advertiser.  # noqa: E501

        :param advertiser_name: The advertiser_name of this AdvertiserOverviewResponse.
        :type advertiser_name: str
        """

        self._advertiser_name = advertiser_name

    @property
    def campaigns(self) -> List[AdvertiserOverviewResponseCampaigns]:
        """Gets the campaigns of this AdvertiserOverviewResponse.


        :return: The campaigns of this AdvertiserOverviewResponse.
        :rtype: List[AdvertiserOverviewResponseCampaigns]
        """
        return self._campaigns

    @campaigns.setter
    def campaigns(self, campaigns: List[AdvertiserOverviewResponseCampaigns]):
        """Sets the campaigns of this AdvertiserOverviewResponse.


        :param campaigns: The campaigns of this AdvertiserOverviewResponse.
        :type campaigns: List[AdvertiserOverviewResponseCampaigns]
        """

        self._campaigns = campaigns

    @property
    def creatives(self) -> List[AdvertiserOverviewResponseCreatives]:
        """Gets the creatives of this AdvertiserOverviewResponse.


        :return: The creatives of this AdvertiserOverviewResponse.
        :rtype: List[AdvertiserOverviewResponseCreatives]
        """
        return self._creatives

    @creatives.setter
    def creatives(self, creatives: List[AdvertiserOverviewResponseCreatives]):
        """Sets the creatives of this AdvertiserOverviewResponse.


        :param creatives: The creatives of this AdvertiserOverviewResponse.
        :type creatives: List[AdvertiserOverviewResponseCreatives]
        """

        self._creatives = creatives
