# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BidListRequestBidLines(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ad_bug_page_quality_category_id: str=None, ad_format_id: str=None, bid_adjustment: float=None, domain_fragment: str=None):  # noqa: E501
        """BidListRequestBidLines - a model defined in Swagger

        :param ad_bug_page_quality_category_id: The ad_bug_page_quality_category_id of this BidListRequestBidLines.  # noqa: E501
        :type ad_bug_page_quality_category_id: str
        :param ad_format_id: The ad_format_id of this BidListRequestBidLines.  # noqa: E501
        :type ad_format_id: str
        :param bid_adjustment: The bid_adjustment of this BidListRequestBidLines.  # noqa: E501
        :type bid_adjustment: float
        :param domain_fragment: The domain_fragment of this BidListRequestBidLines.  # noqa: E501
        :type domain_fragment: str
        """
        self.swagger_types = {
            'ad_bug_page_quality_category_id': str,
            'ad_format_id': str,
            'bid_adjustment': float,
            'domain_fragment': str
        }

        self.attribute_map = {
            'ad_bug_page_quality_category_id': 'AdBugPageQualityCategoryId',
            'ad_format_id': 'AdFormatId',
            'bid_adjustment': 'BidAdjustment',
            'domain_fragment': 'DomainFragment'
        }
        self._ad_bug_page_quality_category_id = ad_bug_page_quality_category_id
        self._ad_format_id = ad_format_id
        self._bid_adjustment = bid_adjustment
        self._domain_fragment = domain_fragment

    @classmethod
    def from_dict(cls, dikt) -> 'BidListRequestBidLines':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BidListRequest_BidLines of this BidListRequestBidLines.  # noqa: E501
        :rtype: BidListRequestBidLines
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ad_bug_page_quality_category_id(self) -> str:
        """Gets the ad_bug_page_quality_category_id of this BidListRequestBidLines.

        The ID of the AdBug Page Quality category to target.  # noqa: E501

        :return: The ad_bug_page_quality_category_id of this BidListRequestBidLines.
        :rtype: str
        """
        return self._ad_bug_page_quality_category_id

    @ad_bug_page_quality_category_id.setter
    def ad_bug_page_quality_category_id(self, ad_bug_page_quality_category_id: str):
        """Sets the ad_bug_page_quality_category_id of this BidListRequestBidLines.

        The ID of the AdBug Page Quality category to target.  # noqa: E501

        :param ad_bug_page_quality_category_id: The ad_bug_page_quality_category_id of this BidListRequestBidLines.
        :type ad_bug_page_quality_category_id: str
        """

        self._ad_bug_page_quality_category_id = ad_bug_page_quality_category_id

    @property
    def ad_format_id(self) -> str:
        """Gets the ad_format_id of this BidListRequestBidLines.

        The Ad Format to be used for this bid line adjustment.  # noqa: E501

        :return: The ad_format_id of this BidListRequestBidLines.
        :rtype: str
        """
        return self._ad_format_id

    @ad_format_id.setter
    def ad_format_id(self, ad_format_id: str):
        """Sets the ad_format_id of this BidListRequestBidLines.

        The Ad Format to be used for this bid line adjustment.  # noqa: E501

        :param ad_format_id: The ad_format_id of this BidListRequestBidLines.
        :type ad_format_id: str
        """

        self._ad_format_id = ad_format_id

    @property
    def bid_adjustment(self) -> float:
        """Gets the bid_adjustment of this BidListRequestBidLines.

        The adjustment to be applied when everything in this BidLine is matched.  # noqa: E501

        :return: The bid_adjustment of this BidListRequestBidLines.
        :rtype: float
        """
        return self._bid_adjustment

    @bid_adjustment.setter
    def bid_adjustment(self, bid_adjustment: float):
        """Sets the bid_adjustment of this BidListRequestBidLines.

        The adjustment to be applied when everything in this BidLine is matched.  # noqa: E501

        :param bid_adjustment: The bid_adjustment of this BidListRequestBidLines.
        :type bid_adjustment: float
        """
        if bid_adjustment is None:
            raise ValueError("Invalid value for `bid_adjustment`, must not be `None`")  # noqa: E501

        self._bid_adjustment = bid_adjustment

    @property
    def domain_fragment(self) -> str:
        """Gets the domain_fragment of this BidListRequestBidLines.

        The domain or app ID to match for this adjustment.  # noqa: E501

        :return: The domain_fragment of this BidListRequestBidLines.
        :rtype: str
        """
        return self._domain_fragment

    @domain_fragment.setter
    def domain_fragment(self, domain_fragment: str):
        """Sets the domain_fragment of this BidListRequestBidLines.

        The domain or app ID to match for this adjustment.  # noqa: E501

        :param domain_fragment: The domain_fragment of this BidListRequestBidLines.
        :type domain_fragment: str
        """
        if domain_fragment is None:
            raise ValueError("Invalid value for `domain_fragment`, must not be `None`")  # noqa: E501

        self._domain_fragment = domain_fragment
