# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CampaignRequestBudget(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount: float=None, currency_code: str=None):  # noqa: E501
        """CampaignRequestBudget - a model defined in Swagger

        :param amount: The amount of this CampaignRequestBudget.  # noqa: E501
        :type amount: float
        :param currency_code: The currency_code of this CampaignRequestBudget.  # noqa: E501
        :type currency_code: str
        """
        self.swagger_types = {
            'amount': float,
            'currency_code': str
        }

        self.attribute_map = {
            'amount': 'Amount',
            'currency_code': 'CurrencyCode'
        }
        self._amount = amount
        self._currency_code = currency_code

    @classmethod
    def from_dict(cls, dikt) -> 'CampaignRequestBudget':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CampaignRequest_Budget of this CampaignRequestBudget.  # noqa: E501
        :rtype: CampaignRequestBudget
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self) -> float:
        """Gets the amount of this CampaignRequestBudget.

        The maximum amount the campaign may spend.  # noqa: E501

        :return: The amount of this CampaignRequestBudget.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this CampaignRequestBudget.

        The maximum amount the campaign may spend.  # noqa: E501

        :param amount: The amount of this CampaignRequestBudget.
        :type amount: float
        """

        self._amount = amount

    @property
    def currency_code(self) -> str:
        """Gets the currency_code of this CampaignRequestBudget.

        The currency of the money value specified in the Amount.  # noqa: E501

        :return: The currency_code of this CampaignRequestBudget.
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code: str):
        """Sets the currency_code of this CampaignRequestBudget.

        The currency of the money value specified in the Amount.  # noqa: E501

        :param currency_code: The currency_code of this CampaignRequestBudget.
        :type currency_code: str
        """

        self._currency_code = currency_code
