# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.campaign_metrics_response_goal_info_cpain_advertiser_currency import CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency  # noqa: F401,E501
from swagger_server.models.campaign_metrics_response_goal_info_ctrin_percent import CampaignMetricsResponseGoalInfoCTRInPercent  # noqa: F401,E501
from swagger_server import util


class CampaignMetricsResponseGoalInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cpain_advertiser_currency: CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency=None, cpcin_advertiser_currency: CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency=None, ctrin_percent: CampaignMetricsResponseGoalInfoCTRInPercent=None, impressions: int=None, last_calculated_at: datetime=None):  # noqa: E501
        """CampaignMetricsResponseGoalInfo - a model defined in Swagger

        :param cpain_advertiser_currency: The cpain_advertiser_currency of this CampaignMetricsResponseGoalInfo.  # noqa: E501
        :type cpain_advertiser_currency: CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency
        :param cpcin_advertiser_currency: The cpcin_advertiser_currency of this CampaignMetricsResponseGoalInfo.  # noqa: E501
        :type cpcin_advertiser_currency: CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency
        :param ctrin_percent: The ctrin_percent of this CampaignMetricsResponseGoalInfo.  # noqa: E501
        :type ctrin_percent: CampaignMetricsResponseGoalInfoCTRInPercent
        :param impressions: The impressions of this CampaignMetricsResponseGoalInfo.  # noqa: E501
        :type impressions: int
        :param last_calculated_at: The last_calculated_at of this CampaignMetricsResponseGoalInfo.  # noqa: E501
        :type last_calculated_at: datetime
        """
        self.swagger_types = {
            'cpain_advertiser_currency': CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency,
            'cpcin_advertiser_currency': CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency,
            'ctrin_percent': CampaignMetricsResponseGoalInfoCTRInPercent,
            'impressions': int,
            'last_calculated_at': datetime
        }

        self.attribute_map = {
            'cpain_advertiser_currency': 'CPAInAdvertiserCurrency',
            'cpcin_advertiser_currency': 'CPCInAdvertiserCurrency',
            'ctrin_percent': 'CTRInPercent',
            'impressions': 'Impressions',
            'last_calculated_at': 'LastCalculatedAt'
        }
        self._cpain_advertiser_currency = cpain_advertiser_currency
        self._cpcin_advertiser_currency = cpcin_advertiser_currency
        self._ctrin_percent = ctrin_percent
        self._impressions = impressions
        self._last_calculated_at = last_calculated_at

    @classmethod
    def from_dict(cls, dikt) -> 'CampaignMetricsResponseGoalInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CampaignMetricsResponse_GoalInfo of this CampaignMetricsResponseGoalInfo.  # noqa: E501
        :rtype: CampaignMetricsResponseGoalInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cpain_advertiser_currency(self) -> CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency:
        """Gets the cpain_advertiser_currency of this CampaignMetricsResponseGoalInfo.


        :return: The cpain_advertiser_currency of this CampaignMetricsResponseGoalInfo.
        :rtype: CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency
        """
        return self._cpain_advertiser_currency

    @cpain_advertiser_currency.setter
    def cpain_advertiser_currency(self, cpain_advertiser_currency: CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency):
        """Sets the cpain_advertiser_currency of this CampaignMetricsResponseGoalInfo.


        :param cpain_advertiser_currency: The cpain_advertiser_currency of this CampaignMetricsResponseGoalInfo.
        :type cpain_advertiser_currency: CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency
        """

        self._cpain_advertiser_currency = cpain_advertiser_currency

    @property
    def cpcin_advertiser_currency(self) -> CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency:
        """Gets the cpcin_advertiser_currency of this CampaignMetricsResponseGoalInfo.


        :return: The cpcin_advertiser_currency of this CampaignMetricsResponseGoalInfo.
        :rtype: CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency
        """
        return self._cpcin_advertiser_currency

    @cpcin_advertiser_currency.setter
    def cpcin_advertiser_currency(self, cpcin_advertiser_currency: CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency):
        """Sets the cpcin_advertiser_currency of this CampaignMetricsResponseGoalInfo.


        :param cpcin_advertiser_currency: The cpcin_advertiser_currency of this CampaignMetricsResponseGoalInfo.
        :type cpcin_advertiser_currency: CampaignMetricsResponseGoalInfoCPAInAdvertiserCurrency
        """

        self._cpcin_advertiser_currency = cpcin_advertiser_currency

    @property
    def ctrin_percent(self) -> CampaignMetricsResponseGoalInfoCTRInPercent:
        """Gets the ctrin_percent of this CampaignMetricsResponseGoalInfo.


        :return: The ctrin_percent of this CampaignMetricsResponseGoalInfo.
        :rtype: CampaignMetricsResponseGoalInfoCTRInPercent
        """
        return self._ctrin_percent

    @ctrin_percent.setter
    def ctrin_percent(self, ctrin_percent: CampaignMetricsResponseGoalInfoCTRInPercent):
        """Sets the ctrin_percent of this CampaignMetricsResponseGoalInfo.


        :param ctrin_percent: The ctrin_percent of this CampaignMetricsResponseGoalInfo.
        :type ctrin_percent: CampaignMetricsResponseGoalInfoCTRInPercent
        """

        self._ctrin_percent = ctrin_percent

    @property
    def impressions(self) -> int:
        """Gets the impressions of this CampaignMetricsResponseGoalInfo.

        Total number of impressions  # noqa: E501

        :return: The impressions of this CampaignMetricsResponseGoalInfo.
        :rtype: int
        """
        return self._impressions

    @impressions.setter
    def impressions(self, impressions: int):
        """Sets the impressions of this CampaignMetricsResponseGoalInfo.

        Total number of impressions  # noqa: E501

        :param impressions: The impressions of this CampaignMetricsResponseGoalInfo.
        :type impressions: int
        """

        self._impressions = impressions

    @property
    def last_calculated_at(self) -> datetime:
        """Gets the last_calculated_at of this CampaignMetricsResponseGoalInfo.

        The last time the goals were calculated  # noqa: E501

        :return: The last_calculated_at of this CampaignMetricsResponseGoalInfo.
        :rtype: datetime
        """
        return self._last_calculated_at

    @last_calculated_at.setter
    def last_calculated_at(self, last_calculated_at: datetime):
        """Sets the last_calculated_at of this CampaignMetricsResponseGoalInfo.

        The last time the goals were calculated  # noqa: E501

        :param last_calculated_at: The last_calculated_at of this CampaignMetricsResponseGoalInfo.
        :type last_calculated_at: datetime
        """

        self._last_calculated_at = last_calculated_at
