# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.campaign_request_budget import CampaignRequestBudget  # noqa: F401,E501
from swagger_server import util


class CampaignResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, campaign_id: str=None, advertiser_id: str=None, campaign_name: str=None, budget: CampaignRequestBudget=None, start_date: datetime=None, end_date: datetime=None):  # noqa: E501
        """CampaignResponse - a model defined in Swagger

        :param campaign_id: The campaign_id of this CampaignResponse.  # noqa: E501
        :type campaign_id: str
        :param advertiser_id: The advertiser_id of this CampaignResponse.  # noqa: E501
        :type advertiser_id: str
        :param campaign_name: The campaign_name of this CampaignResponse.  # noqa: E501
        :type campaign_name: str
        :param budget: The budget of this CampaignResponse.  # noqa: E501
        :type budget: CampaignRequestBudget
        :param start_date: The start_date of this CampaignResponse.  # noqa: E501
        :type start_date: datetime
        :param end_date: The end_date of this CampaignResponse.  # noqa: E501
        :type end_date: datetime
        """
        self.swagger_types = {
            'campaign_id': str,
            'advertiser_id': str,
            'campaign_name': str,
            'budget': CampaignRequestBudget,
            'start_date': datetime,
            'end_date': datetime
        }

        self.attribute_map = {
            'campaign_id': 'CampaignId',
            'advertiser_id': 'AdvertiserId',
            'campaign_name': 'CampaignName',
            'budget': 'Budget',
            'start_date': 'StartDate',
            'end_date': 'EndDate'
        }
        self._campaign_id = campaign_id
        self._advertiser_id = advertiser_id
        self._campaign_name = campaign_name
        self._budget = budget
        self._start_date = start_date
        self._end_date = end_date

    @classmethod
    def from_dict(cls, dikt) -> 'CampaignResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CampaignResponse of this CampaignResponse.  # noqa: E501
        :rtype: CampaignResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def campaign_id(self) -> str:
        """Gets the campaign_id of this CampaignResponse.

        The ID of the created campaign.  # noqa: E501

        :return: The campaign_id of this CampaignResponse.
        :rtype: str
        """
        return self._campaign_id

    @campaign_id.setter
    def campaign_id(self, campaign_id: str):
        """Sets the campaign_id of this CampaignResponse.

        The ID of the created campaign.  # noqa: E501

        :param campaign_id: The campaign_id of this CampaignResponse.
        :type campaign_id: str
        """

        self._campaign_id = campaign_id

    @property
    def advertiser_id(self) -> str:
        """Gets the advertiser_id of this CampaignResponse.

        The platform ID of the advertiser that owns the campaign.  # noqa: E501

        :return: The advertiser_id of this CampaignResponse.
        :rtype: str
        """
        return self._advertiser_id

    @advertiser_id.setter
    def advertiser_id(self, advertiser_id: str):
        """Sets the advertiser_id of this CampaignResponse.

        The platform ID of the advertiser that owns the campaign.  # noqa: E501

        :param advertiser_id: The advertiser_id of this CampaignResponse.
        :type advertiser_id: str
        """

        self._advertiser_id = advertiser_id

    @property
    def campaign_name(self) -> str:
        """Gets the campaign_name of this CampaignResponse.

        The name of the campaign.  # noqa: E501

        :return: The campaign_name of this CampaignResponse.
        :rtype: str
        """
        return self._campaign_name

    @campaign_name.setter
    def campaign_name(self, campaign_name: str):
        """Sets the campaign_name of this CampaignResponse.

        The name of the campaign.  # noqa: E501

        :param campaign_name: The campaign_name of this CampaignResponse.
        :type campaign_name: str
        """

        self._campaign_name = campaign_name

    @property
    def budget(self) -> CampaignRequestBudget:
        """Gets the budget of this CampaignResponse.


        :return: The budget of this CampaignResponse.
        :rtype: CampaignRequestBudget
        """
        return self._budget

    @budget.setter
    def budget(self, budget: CampaignRequestBudget):
        """Sets the budget of this CampaignResponse.


        :param budget: The budget of this CampaignResponse.
        :type budget: CampaignRequestBudget
        """

        self._budget = budget

    @property
    def start_date(self) -> datetime:
        """Gets the start_date of this CampaignResponse.

        The start date and time in UTC when the campaign should begin spending.  # noqa: E501

        :return: The start_date of this CampaignResponse.
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: datetime):
        """Sets the start_date of this CampaignResponse.

        The start date and time in UTC when the campaign should begin spending.  # noqa: E501

        :param start_date: The start_date of this CampaignResponse.
        :type start_date: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self) -> datetime:
        """Gets the end_date of this CampaignResponse.

        The end date and time in UTC when the campaign should stop spending.  # noqa: E501

        :return: The end_date of this CampaignResponse.
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: datetime):
        """Sets the end_date of this CampaignResponse.

        The end date and time in UTC when the campaign should stop spending.  # noqa: E501

        :param end_date: The end_date of this CampaignResponse.
        :type end_date: datetime
        """

        self._end_date = end_date
