# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.campaign_metrics_response_goal_info import CampaignMetricsResponseGoalInfo  # noqa: F401,E501
from swagger_server import util


class CampaignMetricsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, campaign_flight_id: int=None, campaign_id: str=None, goal_info: CampaignMetricsResponseGoalInfo=None, current_spend_in_advertiser_currency: float=None, flight_budget_in_advertiser_currency: float=None, projected_spend_in_advertiser_currency: float=None):  # noqa: E501
        """CampaignMetricsResponse - a model defined in Swagger

        :param campaign_flight_id: The campaign_flight_id of this CampaignMetricsResponse.  # noqa: E501
        :type campaign_flight_id: int
        :param campaign_id: The campaign_id of this CampaignMetricsResponse.  # noqa: E501
        :type campaign_id: str
        :param goal_info: The goal_info of this CampaignMetricsResponse.  # noqa: E501
        :type goal_info: CampaignMetricsResponseGoalInfo
        :param current_spend_in_advertiser_currency: The current_spend_in_advertiser_currency of this CampaignMetricsResponse.  # noqa: E501
        :type current_spend_in_advertiser_currency: float
        :param flight_budget_in_advertiser_currency: The flight_budget_in_advertiser_currency of this CampaignMetricsResponse.  # noqa: E501
        :type flight_budget_in_advertiser_currency: float
        :param projected_spend_in_advertiser_currency: The projected_spend_in_advertiser_currency of this CampaignMetricsResponse.  # noqa: E501
        :type projected_spend_in_advertiser_currency: float
        """
        self.swagger_types = {
            'campaign_flight_id': int,
            'campaign_id': str,
            'goal_info': CampaignMetricsResponseGoalInfo,
            'current_spend_in_advertiser_currency': float,
            'flight_budget_in_advertiser_currency': float,
            'projected_spend_in_advertiser_currency': float
        }

        self.attribute_map = {
            'campaign_flight_id': 'CampaignFlightId',
            'campaign_id': 'CampaignId',
            'goal_info': 'GoalInfo',
            'current_spend_in_advertiser_currency': 'CurrentSpendInAdvertiserCurrency',
            'flight_budget_in_advertiser_currency': 'FlightBudgetInAdvertiserCurrency',
            'projected_spend_in_advertiser_currency': 'ProjectedSpendInAdvertiserCurrency'
        }
        self._campaign_flight_id = campaign_flight_id
        self._campaign_id = campaign_id
        self._goal_info = goal_info
        self._current_spend_in_advertiser_currency = current_spend_in_advertiser_currency
        self._flight_budget_in_advertiser_currency = flight_budget_in_advertiser_currency
        self._projected_spend_in_advertiser_currency = projected_spend_in_advertiser_currency

    @classmethod
    def from_dict(cls, dikt) -> 'CampaignMetricsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CampaignMetricsResponse of this CampaignMetricsResponse.  # noqa: E501
        :rtype: CampaignMetricsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def campaign_flight_id(self) -> int:
        """Gets the campaign_flight_id of this CampaignMetricsResponse.

        ID of the campaign's current flight  # noqa: E501

        :return: The campaign_flight_id of this CampaignMetricsResponse.
        :rtype: int
        """
        return self._campaign_flight_id

    @campaign_flight_id.setter
    def campaign_flight_id(self, campaign_flight_id: int):
        """Sets the campaign_flight_id of this CampaignMetricsResponse.

        ID of the campaign's current flight  # noqa: E501

        :param campaign_flight_id: The campaign_flight_id of this CampaignMetricsResponse.
        :type campaign_flight_id: int
        """

        self._campaign_flight_id = campaign_flight_id

    @property
    def campaign_id(self) -> str:
        """Gets the campaign_id of this CampaignMetricsResponse.

        ID of the campaign  # noqa: E501

        :return: The campaign_id of this CampaignMetricsResponse.
        :rtype: str
        """
        return self._campaign_id

    @campaign_id.setter
    def campaign_id(self, campaign_id: str):
        """Sets the campaign_id of this CampaignMetricsResponse.

        ID of the campaign  # noqa: E501

        :param campaign_id: The campaign_id of this CampaignMetricsResponse.
        :type campaign_id: str
        """

        self._campaign_id = campaign_id

    @property
    def goal_info(self) -> CampaignMetricsResponseGoalInfo:
        """Gets the goal_info of this CampaignMetricsResponse.


        :return: The goal_info of this CampaignMetricsResponse.
        :rtype: CampaignMetricsResponseGoalInfo
        """
        return self._goal_info

    @goal_info.setter
    def goal_info(self, goal_info: CampaignMetricsResponseGoalInfo):
        """Sets the goal_info of this CampaignMetricsResponse.


        :param goal_info: The goal_info of this CampaignMetricsResponse.
        :type goal_info: CampaignMetricsResponseGoalInfo
        """

        self._goal_info = goal_info

    @property
    def current_spend_in_advertiser_currency(self) -> float:
        """Gets the current_spend_in_advertiser_currency of this CampaignMetricsResponse.

        The amount of the budget already spent  # noqa: E501

        :return: The current_spend_in_advertiser_currency of this CampaignMetricsResponse.
        :rtype: float
        """
        return self._current_spend_in_advertiser_currency

    @current_spend_in_advertiser_currency.setter
    def current_spend_in_advertiser_currency(self, current_spend_in_advertiser_currency: float):
        """Sets the current_spend_in_advertiser_currency of this CampaignMetricsResponse.

        The amount of the budget already spent  # noqa: E501

        :param current_spend_in_advertiser_currency: The current_spend_in_advertiser_currency of this CampaignMetricsResponse.
        :type current_spend_in_advertiser_currency: float
        """

        self._current_spend_in_advertiser_currency = current_spend_in_advertiser_currency

    @property
    def flight_budget_in_advertiser_currency(self) -> float:
        """Gets the flight_budget_in_advertiser_currency of this CampaignMetricsResponse.

        The budget of the active flight  # noqa: E501

        :return: The flight_budget_in_advertiser_currency of this CampaignMetricsResponse.
        :rtype: float
        """
        return self._flight_budget_in_advertiser_currency

    @flight_budget_in_advertiser_currency.setter
    def flight_budget_in_advertiser_currency(self, flight_budget_in_advertiser_currency: float):
        """Sets the flight_budget_in_advertiser_currency of this CampaignMetricsResponse.

        The budget of the active flight  # noqa: E501

        :param flight_budget_in_advertiser_currency: The flight_budget_in_advertiser_currency of this CampaignMetricsResponse.
        :type flight_budget_in_advertiser_currency: float
        """

        self._flight_budget_in_advertiser_currency = flight_budget_in_advertiser_currency

    @property
    def projected_spend_in_advertiser_currency(self) -> float:
        """Gets the projected_spend_in_advertiser_currency of this CampaignMetricsResponse.

        Projected spend that was calculated so far  # noqa: E501

        :return: The projected_spend_in_advertiser_currency of this CampaignMetricsResponse.
        :rtype: float
        """
        return self._projected_spend_in_advertiser_currency

    @projected_spend_in_advertiser_currency.setter
    def projected_spend_in_advertiser_currency(self, projected_spend_in_advertiser_currency: float):
        """Sets the projected_spend_in_advertiser_currency of this CampaignMetricsResponse.

        Projected spend that was calculated so far  # noqa: E501

        :param projected_spend_in_advertiser_currency: The projected_spend_in_advertiser_currency of this CampaignMetricsResponse.
        :type projected_spend_in_advertiser_currency: float
        """

        self._projected_spend_in_advertiser_currency = projected_spend_in_advertiser_currency
