# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CampaignMetricsResponseGoalInfoCTRInPercent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount: float=None, target: float=None):  # noqa: E501
        """CampaignMetricsResponseGoalInfoCTRInPercent - a model defined in Swagger

        :param amount: The amount of this CampaignMetricsResponseGoalInfoCTRInPercent.  # noqa: E501
        :type amount: float
        :param target: The target of this CampaignMetricsResponseGoalInfoCTRInPercent.  # noqa: E501
        :type target: float
        """
        self.swagger_types = {
            'amount': float,
            'target': float
        }

        self.attribute_map = {
            'amount': 'Amount',
            'target': 'Target'
        }
        self._amount = amount
        self._target = target

    @classmethod
    def from_dict(cls, dikt) -> 'CampaignMetricsResponseGoalInfoCTRInPercent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CampaignMetricsResponse_GoalInfo_CTRInPercent of this CampaignMetricsResponseGoalInfoCTRInPercent.  # noqa: E501
        :rtype: CampaignMetricsResponseGoalInfoCTRInPercent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self) -> float:
        """Gets the amount of this CampaignMetricsResponseGoalInfoCTRInPercent.

        The average click-through rate in percent  # noqa: E501

        :return: The amount of this CampaignMetricsResponseGoalInfoCTRInPercent.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this CampaignMetricsResponseGoalInfoCTRInPercent.

        The average click-through rate in percent  # noqa: E501

        :param amount: The amount of this CampaignMetricsResponseGoalInfoCTRInPercent.
        :type amount: float
        """

        self._amount = amount

    @property
    def target(self) -> float:
        """Gets the target of this CampaignMetricsResponseGoalInfoCTRInPercent.

        The target for this goal  # noqa: E501

        :return: The target of this CampaignMetricsResponseGoalInfoCTRInPercent.
        :rtype: float
        """
        return self._target

    @target.setter
    def target(self, target: float):
        """Sets the target of this CampaignMetricsResponseGoalInfoCTRInPercent.

        The target for this goal  # noqa: E501

        :param target: The target of this CampaignMetricsResponseGoalInfoCTRInPercent.
        :type target: float
        """

        self._target = target
