# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.campaign_request_budget import CampaignRequestBudget  # noqa: F401,E501
from swagger_server.models.campaign_request_primary_goal import CampaignRequestPrimaryGoal  # noqa: F401,E501
from swagger_server import util


class CampaignRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, advertiser_id: str=None, campaign_name: str=None, budget: CampaignRequestBudget=None, start_date: datetime=None, end_date: datetime=None, primary_goal: CampaignRequestPrimaryGoal=None, tracking_tags: List[str]=None):  # noqa: E501
        """CampaignRequest - a model defined in Swagger

        :param advertiser_id: The advertiser_id of this CampaignRequest.  # noqa: E501
        :type advertiser_id: str
        :param campaign_name: The campaign_name of this CampaignRequest.  # noqa: E501
        :type campaign_name: str
        :param budget: The budget of this CampaignRequest.  # noqa: E501
        :type budget: CampaignRequestBudget
        :param start_date: The start_date of this CampaignRequest.  # noqa: E501
        :type start_date: datetime
        :param end_date: The end_date of this CampaignRequest.  # noqa: E501
        :type end_date: datetime
        :param primary_goal: The primary_goal of this CampaignRequest.  # noqa: E501
        :type primary_goal: CampaignRequestPrimaryGoal
        :param tracking_tags: The tracking_tags of this CampaignRequest.  # noqa: E501
        :type tracking_tags: List[str]
        """
        self.swagger_types = {
            'advertiser_id': str,
            'campaign_name': str,
            'budget': CampaignRequestBudget,
            'start_date': datetime,
            'end_date': datetime,
            'primary_goal': CampaignRequestPrimaryGoal,
            'tracking_tags': List[str]
        }

        self.attribute_map = {
            'advertiser_id': 'AdvertiserId',
            'campaign_name': 'CampaignName',
            'budget': 'Budget',
            'start_date': 'StartDate',
            'end_date': 'EndDate',
            'primary_goal': 'PrimaryGoal',
            'tracking_tags': 'TrackingTags'
        }
        self._advertiser_id = advertiser_id
        self._campaign_name = campaign_name
        self._budget = budget
        self._start_date = start_date
        self._end_date = end_date
        self._primary_goal = primary_goal
        self._tracking_tags = tracking_tags

    @classmethod
    def from_dict(cls, dikt) -> 'CampaignRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CampaignRequest of this CampaignRequest.  # noqa: E501
        :rtype: CampaignRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def advertiser_id(self) -> str:
        """Gets the advertiser_id of this CampaignRequest.

        The platform ID of the advertiser that owns this campaign.  # noqa: E501

        :return: The advertiser_id of this CampaignRequest.
        :rtype: str
        """
        return self._advertiser_id

    @advertiser_id.setter
    def advertiser_id(self, advertiser_id: str):
        """Sets the advertiser_id of this CampaignRequest.

        The platform ID of the advertiser that owns this campaign.  # noqa: E501

        :param advertiser_id: The advertiser_id of this CampaignRequest.
        :type advertiser_id: str
        """
        if advertiser_id is None:
            raise ValueError("Invalid value for `advertiser_id`, must not be `None`")  # noqa: E501

        self._advertiser_id = advertiser_id

    @property
    def campaign_name(self) -> str:
        """Gets the campaign_name of this CampaignRequest.

        The name of the campaign.  # noqa: E501

        :return: The campaign_name of this CampaignRequest.
        :rtype: str
        """
        return self._campaign_name

    @campaign_name.setter
    def campaign_name(self, campaign_name: str):
        """Sets the campaign_name of this CampaignRequest.

        The name of the campaign.  # noqa: E501

        :param campaign_name: The campaign_name of this CampaignRequest.
        :type campaign_name: str
        """
        if campaign_name is None:
            raise ValueError("Invalid value for `campaign_name`, must not be `None`")  # noqa: E501

        self._campaign_name = campaign_name

    @property
    def budget(self) -> CampaignRequestBudget:
        """Gets the budget of this CampaignRequest.


        :return: The budget of this CampaignRequest.
        :rtype: CampaignRequestBudget
        """
        return self._budget

    @budget.setter
    def budget(self, budget: CampaignRequestBudget):
        """Sets the budget of this CampaignRequest.


        :param budget: The budget of this CampaignRequest.
        :type budget: CampaignRequestBudget
        """
        if budget is None:
            raise ValueError("Invalid value for `budget`, must not be `None`")  # noqa: E501

        self._budget = budget

    @property
    def start_date(self) -> datetime:
        """Gets the start_date of this CampaignRequest.

        The start date and time in UTC when the campaign should begin spending.  # noqa: E501

        :return: The start_date of this CampaignRequest.
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: datetime):
        """Sets the start_date of this CampaignRequest.

        The start date and time in UTC when the campaign should begin spending.  # noqa: E501

        :param start_date: The start_date of this CampaignRequest.
        :type start_date: datetime
        """
        if start_date is None:
            raise ValueError("Invalid value for `start_date`, must not be `None`")  # noqa: E501

        self._start_date = start_date

    @property
    def end_date(self) -> datetime:
        """Gets the end_date of this CampaignRequest.

        The end date and time in UTC when the campaign should stop spending.  # noqa: E501

        :return: The end_date of this CampaignRequest.
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: datetime):
        """Sets the end_date of this CampaignRequest.

        The end date and time in UTC when the campaign should stop spending.  # noqa: E501

        :param end_date: The end_date of this CampaignRequest.
        :type end_date: datetime
        """

        self._end_date = end_date

    @property
    def primary_goal(self) -> CampaignRequestPrimaryGoal:
        """Gets the primary_goal of this CampaignRequest.


        :return: The primary_goal of this CampaignRequest.
        :rtype: CampaignRequestPrimaryGoal
        """
        return self._primary_goal

    @primary_goal.setter
    def primary_goal(self, primary_goal: CampaignRequestPrimaryGoal):
        """Sets the primary_goal of this CampaignRequest.


        :param primary_goal: The primary_goal of this CampaignRequest.
        :type primary_goal: CampaignRequestPrimaryGoal
        """

        self._primary_goal = primary_goal

    @property
    def tracking_tags(self) -> List[str]:
        """Gets the tracking_tags of this CampaignRequest.

        List of tracking tags associated with the campaign.  # noqa: E501

        :return: The tracking_tags of this CampaignRequest.
        :rtype: List[str]
        """
        return self._tracking_tags

    @tracking_tags.setter
    def tracking_tags(self, tracking_tags: List[str]):
        """Sets the tracking_tags of this CampaignRequest.

        List of tracking tags associated with the campaign.  # noqa: E501

        :param tracking_tags: The tracking_tags of this CampaignRequest.
        :type tracking_tags: List[str]
        """

        self._tracking_tags = tracking_tags
