# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FirstPartyAdvertiserRequestSortFields(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, field_id: str=None, ascending: bool=True):  # noqa: E501
        """FirstPartyAdvertiserRequestSortFields - a model defined in Swagger

        :param field_id: The field_id of this FirstPartyAdvertiserRequestSortFields.  # noqa: E501
        :type field_id: str
        :param ascending: The ascending of this FirstPartyAdvertiserRequestSortFields.  # noqa: E501
        :type ascending: bool
        """
        self.swagger_types = {
            'field_id': str,
            'ascending': bool
        }

        self.attribute_map = {
            'field_id': 'FieldId',
            'ascending': 'Ascending'
        }
        self._field_id = field_id
        self._ascending = ascending

    @classmethod
    def from_dict(cls, dikt) -> 'FirstPartyAdvertiserRequestSortFields':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FirstPartyAdvertiserRequest_SortFields of this FirstPartyAdvertiserRequestSortFields.  # noqa: E501
        :rtype: FirstPartyAdvertiserRequestSortFields
        """
        return util.deserialize_model(dikt, cls)

    @property
    def field_id(self) -> str:
        """Gets the field_id of this FirstPartyAdvertiserRequestSortFields.


        :return: The field_id of this FirstPartyAdvertiserRequestSortFields.
        :rtype: str
        """
        return self._field_id

    @field_id.setter
    def field_id(self, field_id: str):
        """Sets the field_id of this FirstPartyAdvertiserRequestSortFields.


        :param field_id: The field_id of this FirstPartyAdvertiserRequestSortFields.
        :type field_id: str
        """
        allowed_values = ["Name", "DataType", "Uniques"]  # noqa: E501
        if field_id not in allowed_values:
            raise ValueError(
                "Invalid value for `field_id` ({0}), must be one of {1}"
                .format(field_id, allowed_values)
            )

        self._field_id = field_id

    @property
    def ascending(self) -> bool:
        """Gets the ascending of this FirstPartyAdvertiserRequestSortFields.


        :return: The ascending of this FirstPartyAdvertiserRequestSortFields.
        :rtype: bool
        """
        return self._ascending

    @ascending.setter
    def ascending(self, ascending: bool):
        """Sets the ascending of this FirstPartyAdvertiserRequestSortFields.


        :param ascending: The ascending of this FirstPartyAdvertiserRequestSortFields.
        :type ascending: bool
        """

        self._ascending = ascending
