# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.frequency_config_request_bid_lists import FrequencyConfigRequestBidLists  # noqa: F401,E501
from swagger_server.models.frequency_config_request_counter import FrequencyConfigRequestCounter  # noqa: F401,E501
from swagger_server import util


class FrequencyConfigRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, bid_lists: List[FrequencyConfigRequestBidLists]=None, counter: FrequencyConfigRequestCounter=None):  # noqa: E501
        """FrequencyConfigRequest - a model defined in Swagger

        :param bid_lists: The bid_lists of this FrequencyConfigRequest.  # noqa: E501
        :type bid_lists: List[FrequencyConfigRequestBidLists]
        :param counter: The counter of this FrequencyConfigRequest.  # noqa: E501
        :type counter: FrequencyConfigRequestCounter
        """
        self.swagger_types = {
            'bid_lists': List[FrequencyConfigRequestBidLists],
            'counter': FrequencyConfigRequestCounter
        }

        self.attribute_map = {
            'bid_lists': 'BidLists',
            'counter': 'Counter'
        }
        self._bid_lists = bid_lists
        self._counter = counter

    @classmethod
    def from_dict(cls, dikt) -> 'FrequencyConfigRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FrequencyConfigRequest of this FrequencyConfigRequest.  # noqa: E501
        :rtype: FrequencyConfigRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bid_lists(self) -> List[FrequencyConfigRequestBidLists]:
        """Gets the bid_lists of this FrequencyConfigRequest.

        Bid lists apply frequency settings to ad groups, campaigns, and other entities.  # noqa: E501

        :return: The bid_lists of this FrequencyConfigRequest.
        :rtype: List[FrequencyConfigRequestBidLists]
        """
        return self._bid_lists

    @bid_lists.setter
    def bid_lists(self, bid_lists: List[FrequencyConfigRequestBidLists]):
        """Sets the bid_lists of this FrequencyConfigRequest.

        Bid lists apply frequency settings to ad groups, campaigns, and other entities.  # noqa: E501

        :param bid_lists: The bid_lists of this FrequencyConfigRequest.
        :type bid_lists: List[FrequencyConfigRequestBidLists]
        """

        self._bid_lists = bid_lists

    @property
    def counter(self) -> FrequencyConfigRequestCounter:
        """Gets the counter of this FrequencyConfigRequest.


        :return: The counter of this FrequencyConfigRequest.
        :rtype: FrequencyConfigRequestCounter
        """
        return self._counter

    @counter.setter
    def counter(self, counter: FrequencyConfigRequestCounter):
        """Sets the counter of this FrequencyConfigRequest.


        :param counter: The counter of this FrequencyConfigRequest.
        :type counter: FrequencyConfigRequestCounter
        """

        self._counter = counter
