# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response200_metric_results import InlineResponse200MetricResults  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metric_results: List[InlineResponse200MetricResults]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param metric_results: The metric_results of this InlineResponse200.  # noqa: E501
        :type metric_results: List[InlineResponse200MetricResults]
        """
        self.swagger_types = {
            'metric_results': List[InlineResponse200MetricResults]
        }

        self.attribute_map = {
            'metric_results': 'MetricResults'
        }
        self._metric_results = metric_results

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metric_results(self) -> List[InlineResponse200MetricResults]:
        """Gets the metric_results of this InlineResponse200.


        :return: The metric_results of this InlineResponse200.
        :rtype: List[InlineResponse200MetricResults]
        """
        return self._metric_results

    @metric_results.setter
    def metric_results(self, metric_results: List[InlineResponse200MetricResults]):
        """Sets the metric_results of this InlineResponse200.


        :param metric_results: The metric_results of this InlineResponse200.
        :type metric_results: List[InlineResponse200MetricResults]
        """

        self._metric_results = metric_results
