# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.seller_query_response_result import SellerQueryResponseResult  # noqa: F401,E501
from swagger_server import util


class SellerQueryResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result: List[SellerQueryResponseResult]=None, result_count: int=None, total_filtered_count: int=None, total_unfiltered_count: int=None):  # noqa: E501
        """SellerQueryResponse - a model defined in Swagger

        :param result: The result of this SellerQueryResponse.  # noqa: E501
        :type result: List[SellerQueryResponseResult]
        :param result_count: The result_count of this SellerQueryResponse.  # noqa: E501
        :type result_count: int
        :param total_filtered_count: The total_filtered_count of this SellerQueryResponse.  # noqa: E501
        :type total_filtered_count: int
        :param total_unfiltered_count: The total_unfiltered_count of this SellerQueryResponse.  # noqa: E501
        :type total_unfiltered_count: int
        """
        self.swagger_types = {
            'result': List[SellerQueryResponseResult],
            'result_count': int,
            'total_filtered_count': int,
            'total_unfiltered_count': int
        }

        self.attribute_map = {
            'result': 'Result',
            'result_count': 'ResultCount',
            'total_filtered_count': 'TotalFilteredCount',
            'total_unfiltered_count': 'TotalUnfilteredCount'
        }
        self._result = result
        self._result_count = result_count
        self._total_filtered_count = total_filtered_count
        self._total_unfiltered_count = total_unfiltered_count

    @classmethod
    def from_dict(cls, dikt) -> 'SellerQueryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SellerQueryResponse of this SellerQueryResponse.  # noqa: E501
        :rtype: SellerQueryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> List[SellerQueryResponseResult]:
        """Gets the result of this SellerQueryResponse.


        :return: The result of this SellerQueryResponse.
        :rtype: List[SellerQueryResponseResult]
        """
        return self._result

    @result.setter
    def result(self, result: List[SellerQueryResponseResult]):
        """Sets the result of this SellerQueryResponse.


        :param result: The result of this SellerQueryResponse.
        :type result: List[SellerQueryResponseResult]
        """

        self._result = result

    @property
    def result_count(self) -> int:
        """Gets the result_count of this SellerQueryResponse.

        The number of objects returned in the result.  # noqa: E501

        :return: The result_count of this SellerQueryResponse.
        :rtype: int
        """
        return self._result_count

    @result_count.setter
    def result_count(self, result_count: int):
        """Sets the result_count of this SellerQueryResponse.

        The number of objects returned in the result.  # noqa: E501

        :param result_count: The result_count of this SellerQueryResponse.
        :type result_count: int
        """

        self._result_count = result_count

    @property
    def total_filtered_count(self) -> int:
        """Gets the total_filtered_count of this SellerQueryResponse.

        The total number of objects available that match the request filters.  # noqa: E501

        :return: The total_filtered_count of this SellerQueryResponse.
        :rtype: int
        """
        return self._total_filtered_count

    @total_filtered_count.setter
    def total_filtered_count(self, total_filtered_count: int):
        """Sets the total_filtered_count of this SellerQueryResponse.

        The total number of objects available that match the request filters.  # noqa: E501

        :param total_filtered_count: The total_filtered_count of this SellerQueryResponse.
        :type total_filtered_count: int
        """

        self._total_filtered_count = total_filtered_count

    @property
    def total_unfiltered_count(self) -> int:
        """Gets the total_unfiltered_count of this SellerQueryResponse.

        The total number of objects available.  # noqa: E501

        :return: The total_unfiltered_count of this SellerQueryResponse.
        :rtype: int
        """
        return self._total_unfiltered_count

    @total_unfiltered_count.setter
    def total_unfiltered_count(self, total_unfiltered_count: int):
        """Sets the total_unfiltered_count of this SellerQueryResponse.

        The total number of objects available.  # noqa: E501

        :param total_unfiltered_count: The total_unfiltered_count of this SellerQueryResponse.
        :type total_unfiltered_count: int
        """

        self._total_unfiltered_count = total_unfiltered_count
