# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.universal_forecasting_request_bid_lines import UniversalForecastingRequestBidLines  # noqa: F401,E501
from swagger_server import util


class UniversalForecastingRequestUniversalForecastingBidLists(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, bid_lines: List[UniversalForecastingRequestBidLines]=None):  # noqa: E501
        """UniversalForecastingRequestUniversalForecastingBidLists - a model defined in Swagger

        :param bid_lines: The bid_lines of this UniversalForecastingRequestUniversalForecastingBidLists.  # noqa: E501
        :type bid_lines: List[UniversalForecastingRequestBidLines]
        """
        self.swagger_types = {
            'bid_lines': List[UniversalForecastingRequestBidLines]
        }

        self.attribute_map = {
            'bid_lines': 'BidLines'
        }
        self._bid_lines = bid_lines

    @classmethod
    def from_dict(cls, dikt) -> 'UniversalForecastingRequestUniversalForecastingBidLists':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UniversalForecastingRequest_UniversalForecastingBidLists of this UniversalForecastingRequestUniversalForecastingBidLists.  # noqa: E501
        :rtype: UniversalForecastingRequestUniversalForecastingBidLists
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bid_lines(self) -> List[UniversalForecastingRequestBidLines]:
        """Gets the bid_lines of this UniversalForecastingRequestUniversalForecastingBidLists.


        :return: The bid_lines of this UniversalForecastingRequestUniversalForecastingBidLists.
        :rtype: List[UniversalForecastingRequestBidLines]
        """
        return self._bid_lines

    @bid_lines.setter
    def bid_lines(self, bid_lines: List[UniversalForecastingRequestBidLines]):
        """Sets the bid_lines of this UniversalForecastingRequestUniversalForecastingBidLists.


        :param bid_lines: The bid_lines of this UniversalForecastingRequestUniversalForecastingBidLists.
        :type bid_lines: List[UniversalForecastingRequestBidLines]
        """

        self._bid_lines = bid_lines
