# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UniversalForecastingRequestBidLines(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ad_bug_page_quality_category_id: str=None, ad_format_id: str=None, bid_adjustment: float=None):  # noqa: E501
        """UniversalForecastingRequestBidLines - a model defined in Swagger

        :param ad_bug_page_quality_category_id: The ad_bug_page_quality_category_id of this UniversalForecastingRequestBidLines.  # noqa: E501
        :type ad_bug_page_quality_category_id: str
        :param ad_format_id: The ad_format_id of this UniversalForecastingRequestBidLines.  # noqa: E501
        :type ad_format_id: str
        :param bid_adjustment: The bid_adjustment of this UniversalForecastingRequestBidLines.  # noqa: E501
        :type bid_adjustment: float
        """
        self.swagger_types = {
            'ad_bug_page_quality_category_id': str,
            'ad_format_id': str,
            'bid_adjustment': float
        }

        self.attribute_map = {
            'ad_bug_page_quality_category_id': 'AdBugPageQualityCategoryId',
            'ad_format_id': 'AdFormatId',
            'bid_adjustment': 'BidAdjustment'
        }
        self._ad_bug_page_quality_category_id = ad_bug_page_quality_category_id
        self._ad_format_id = ad_format_id
        self._bid_adjustment = bid_adjustment

    @classmethod
    def from_dict(cls, dikt) -> 'UniversalForecastingRequestBidLines':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UniversalForecastingRequest_BidLines of this UniversalForecastingRequestBidLines.  # noqa: E501
        :rtype: UniversalForecastingRequestBidLines
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ad_bug_page_quality_category_id(self) -> str:
        """Gets the ad_bug_page_quality_category_id of this UniversalForecastingRequestBidLines.


        :return: The ad_bug_page_quality_category_id of this UniversalForecastingRequestBidLines.
        :rtype: str
        """
        return self._ad_bug_page_quality_category_id

    @ad_bug_page_quality_category_id.setter
    def ad_bug_page_quality_category_id(self, ad_bug_page_quality_category_id: str):
        """Sets the ad_bug_page_quality_category_id of this UniversalForecastingRequestBidLines.


        :param ad_bug_page_quality_category_id: The ad_bug_page_quality_category_id of this UniversalForecastingRequestBidLines.
        :type ad_bug_page_quality_category_id: str
        """

        self._ad_bug_page_quality_category_id = ad_bug_page_quality_category_id

    @property
    def ad_format_id(self) -> str:
        """Gets the ad_format_id of this UniversalForecastingRequestBidLines.


        :return: The ad_format_id of this UniversalForecastingRequestBidLines.
        :rtype: str
        """
        return self._ad_format_id

    @ad_format_id.setter
    def ad_format_id(self, ad_format_id: str):
        """Sets the ad_format_id of this UniversalForecastingRequestBidLines.


        :param ad_format_id: The ad_format_id of this UniversalForecastingRequestBidLines.
        :type ad_format_id: str
        """

        self._ad_format_id = ad_format_id

    @property
    def bid_adjustment(self) -> float:
        """Gets the bid_adjustment of this UniversalForecastingRequestBidLines.


        :return: The bid_adjustment of this UniversalForecastingRequestBidLines.
        :rtype: float
        """
        return self._bid_adjustment

    @bid_adjustment.setter
    def bid_adjustment(self, bid_adjustment: float):
        """Sets the bid_adjustment of this UniversalForecastingRequestBidLines.


        :param bid_adjustment: The bid_adjustment of this UniversalForecastingRequestBidLines.
        :type bid_adjustment: float
        """

        self._bid_adjustment = bid_adjustment
